#include "portNames.h"

const char* getPortName(uint16_t port)
{
	switch(port)
	{
		case    0: return "Shirt Pocket netTunes. Shirt Pocket launchTunes.";
		case    1: return "TCPMUX, TCP Port Service Multiplexer.";
		case    2: return "Management Utility.";
		case    3: return "Compression Process.";
		case    5: return "Remote Job Entry.";
		case    7: return "Echo.";
		case    9: return "Discard.";
		case    11: return "SYSTAT.";
		case    13: return "Daytime.";
		case    15: return "[was netstat].";
		case    17: return "Quote, Quote of the Day.";
		case    18: return "RWP, Remote Write Protocol. Send, Message Send Protocol.";
		case    19: return "Chargen, Character Generator Protocol.";
		case    20: return "FTP, File Transfer Protocol, data.";
		case    21: return "FTP, File Transfer Protocol, control.";
		case    22: return "SSH.";
		case    23: return "Telnet.";
		case    24: return "Any private mail system.";
		case    25: return "SMTP, Simple Mail Transfer Protocol.";
		case    27: return "NSW User System FE.";
		case    29: return "MSG ICP.";
		case    31: return "MSG Authentication.";
		case    33: return "Display Support Protocol.";
		case    35: return "Any private printer server.";
		case    37: return "Time, Time Protocol.";
		case    38: return "RAP, Internet Route Access Protocol.";
		case    39: return "RLP, Resource Location Protocol.";
		case    41: return "Graphics.";
		case    42: return "Internet Name Server.";
		case    43: return "Whois.";
		case    44: return "MPM FLAGS Protocol.";
		case    45: return "Internet Message Protocol.";
		case    46: return "MPM [default send].";
		case    47: return "NI FTP.";
		case    48: return "Digital Audit Daemon.";
		case    49: return "TACACS. TACACS+.";
		case    50: return "RMCP, Remote Mail Checking Protocol.";
		case    51: return "IMP Logical Address Maintenance.";
		case    52: return "XNS Time Protocol.";
		case    53: return "DNS, Domain Name System.";
		case    54: return "XNS Clearinghouse.";
		case    55: return "ISI Graphics Language.";
		case    56: return "XNS Authentication.";
		case    57: return "MTP, Mail Transfer Protocol.";
		case    58: return "XNS Mail.";
		case    59: return "NFILE.";
		case    61: return "NI MAIL.";
		case    62: return "ACA Services.";
		case    63: return "Whois++.";
		case    64: return "Communications Integrator (CI).";
		case    65: return "TACACS-Database Service.";
		case    66: return "Oracle SQL*NET.";
		case    67: return "BOOTP, Bootstrap Protocol, server.";
		case    68: return "BOOTP, Bootstrap Protocol, client.";
		case    69: return "TFTP, Trivial File Transfer Protocol.";
		case    70: return "Gopher.";
		case    71: return "Remote Job Service.";
		case    72: return "Remote Job Service.";
		case    73: return "Remote Job Service.";
		case    74: return "Remote Job Service.";
		case    75: return "Any private dial out service.";
		case    76: return "Distributed External Object Store.";
		case    77: return "Any private RJE service.";
		case    78: return "vettcp.";
		case    79: return "Finger.";
		case    80: return "HTTP, HyperText Transfer Protocol.";
		case    81: return "HOSTS2 Name Server.";
		case    82: return "XFER Utility.";
		case    83: return "MIT ML Device.";
		case    84: return "Common Trace Facility.";
		case    85: return "MIT ML Device.";
		case    86: return "Micro Focus Cobol.";
		case    87: return "Any private terminal link.";
		case    88: return "Kerberos.";
		case    89: return "SU/MIT Telnet Gateway.";
		case    90: return "Is being used unofficially by Pointcast. DNSIX Securit Attribute Token Map.";
		case    91: return "MIT Dover Spooler.";
		case    92: return "Network Printing Protocol.";
		case    93: return "Device Control Protocol.";
		case    94: return "Tivoli Object Dispatcher.";
		case    95: return "SUPDUP.";
		case    96: return "DIXIE.";
		case    97: return "Swift Remote Virtual File Protocol.";
		case    98: return "TAC News.";
		case    99: return "Metagram Relay.";
		case    100: return "[unauthorized use]";
		case    101: return "HOSTNAME.";
		case    102: return "TP0 over TCP.";
		case    103: return "Genesis Point-to-Point Trans Net.";
		case    104: return "ACR-NEMA Digital Imag. &amp; Comm. 300.";
		case    105: return "Ph. Mailbox Name Nameserver.";
		case    106: return "3COM-TSMUX.";
		case    107: return "Remote  Telnet Service.";
		case    108: return "SNA Gateway Access Server.";
		case    109: return "POP, Post Office Protocol, version 2.";
		case    110: return "POP, Post Office Protocol, version 3.";
		case    111: return "Portmapper.";
		case    112: return "McIDAS Data Transmission Protocol.";
		case    113: return "Identification Protocol.";
		case    115: return "SFTP, Simple File Transfer Protocol.";
		case    116: return "ANSA REX Notify.";
		case    117: return "UUCP, Unix To Unix Copy.";
		case    118: return "SQL Services.";
		case    119: return "NNTP, Network News Transfer Protocol.";
		case    120: return "CFDP, Coherent File Distribution Protocol.";
		case    121: return "Encore Expedited Remote Pro.Call.";
		case    122: return "SMAKYNET.";
		case    123: return "NTP, Network Time Protocol.";
		case    124: return "ANSA REX Trader.";
		case    125: return "Locus PC-Interface Net Map Serv.";
		case    126: return "Unisys Unitary Login.";
		case    127: return "Locus PC-Interface Conn Server.";
		case    128: return "GSS X License Verification.";
		case    129: return "PWDGEN, Password Generator Protocol.";
		case    130: return "cisco FNATIVE.";
		case    131: return "cisco TNATIVE.";
		case    132: return "cisco SYSMAINT.";
		case    133: return "STATSRV, Statistics Server.";
		case    134: return "INGRES-NET Service.";
		case    135: return "DCE endpoint resolution.";
		case    136: return "PROFILE Naming System.";
		case    137: return "NETBIOS Name Service.";
		case    138: return "NETBIOS Datagram Service.";
		case    139: return "NETBIOS Session Service.";
		case    140: return "EMFIS Data Service.";
		case    141: return "EMFIS Control Service.";
		case    142: return "Britton-Lee IDM.";
		case    143: return "IMAP, Interactive Mail Access Protocol.";
		case    144: return "Universal Management Architecture.";
		case    145: return "UAAC Protocol.";
		case    146: return "TP0 bridge between TCP and X.25.";
		case    147: return "ISO-IP.";
		case    148: return "Jargon.";
		case    149: return "AED 512 Emulation Service.";
		case    150: return "SQL-NET.";
		case    151: return "HEMS.";
		case    152: return "BFTP, Background File Transfer Program.";
		case    153: return "SGMP, Simple Gateway Monitoring Protocol.";
		case    154: return "NETSC.";
		case    155: return "NETSC.";
		case    156: return "SQL Service.";
		case    157: return "KNET/VM Command/Message Protocol.";
		case    158: return "DMSP, Distributed Mail Service Protocol.";
		case    159: return "NSS-Routing.";
		case    160: return "SGMP-TRAPS.";
		case    161: return "SNMP, Simple Network Management Protocol.";
		case    162: return "SNMP, Simple Network Management Protocol traps.";
		case    163: return "CMIP/TCP Manager.";
		case    164: return "CMIP/TCP Agent.";
		case    165: return "Xerox. ";
		case    166: return "Sirius Systems. ";
		case    167: return "NAMP. ";
		case    168: return "RSVD. ";
		case    169: return "SEND.";
		case    170: return "Network PostScript.";
		case    171: return "Network Innovations Multiplex.";
		case    172: return "Network Innovations CL/1. ";
		case    173: return "Xyplex.";
		case    174: return "MAILQ. ";
		case    175: return "VMNET. ";
		case    176: return "GENRAD-MUX.";
		case    177: return "XDMCP, X Display Manager Control Protocol. ";
		case    178: return "NextStep Window Server. ";
		case    179: return "BGP, Border Gateway Protocol.";
		case    180: return "Intergraph.";
		case    181: return "Unify. ";
		case    182: return "Unisys Audit SITP. ";
		case    183: return "OCBinder. ";
		case    184: return "OCServer. ";
		case    185: return "Knowbot Information Service.";
		case    186: return "KIS Protocol. ";
		case    187: return "Application Communication Interface.";
		case    188: return "Plus Five's MUMPS. ";
		case    189: return "Queued File Transport. ";
		case    190: return "Gateway Access Control Protocol.";
		case    191: return "Prospero Directory Service. ";
		case    192: return "OSU Network Monitoring System. ";
		case    193: return "Spider Remote Monitoring Protocol. ";
		case    194: return "Internet Relay Chat Protocol.";
		case    195: return "DNSIX Network Level Module Audit.";
		case    196: return "DNSIX Session Mgt Module Audit Redir.";
		case    197: return "Directory Location Service.";
		case    198: return "Directory Location Service Monitor.";
		case    199: return "SMUX.";
		case    200: return "IBM System Resource Controller.";
		case    201: return "AppleTalk Routing Maintenance.";
		case    202: return "AppleTalk Name Binding.";
		case    203: return "AppleTalk Unused. ";
		case    204: return "AppleTalk Echo. ";
		case    205: return "AppleTalk Unused. ";
		case    206: return "AppleTalk Zone Information. ";
		case    207: return "AppleTalk Unused. ";
		case    208: return "AppleTalk Unused. ";
		case    209: return "The Quick Mail Transfer Protocol.";
		case    210: return "Z39.50.";
		case    211: return "Texas Instruments 914C/G Terminal.";
		case    212: return "ATEXSSTR.";
		case    213: return "IPX.";
		case    214: return "VM PWSCS.";
		case    215: return "Insignia Solutions.";
		case    216: return "Computer Associates Int'l License Server.";
		case    217: return "dBASE Unix.";
		case    218: return "MPP, Message Posting Protocol.";
		case    219: return "Unisys ARPs.";
		case    220: return "IMAP, Interactive Mail Access Protocol, version 3.";
		case    221: return "Berkeley rlogind with SPX auth.";
		case    222: return "Berkeley rshd with SPX auth.";
		case    223: return "Certificate Distribution Center. ";
		case    242: return "Direct.";
		case    243: return "Survey Measurement. ";
		case    244: return "Dayna.";
		case    245: return "LINK.";
		case    246: return "Display Systems Protocol. ";
		case    247: return "SUBNTBCST_TFTP.";
		case    248: return "bhfhs.";
		case    256: return "RAP.";
		case    257: return "Secure Electronic Transaction.";
		case    258: return "Yak Winsock Personal Chat.";
		case    259: return "ESRO, Efficient Short Remote Operations.";
		case    260: return "Openport.";
		case    261: return "IIOP Name Service over TLS/SSL.";
		case    262: return "Arcisdms.";
		case    263: return "HDAP.";
		case    264: return "BGMP, Border Gateway Multicast Protocol.";
		case    265: return "X-Bone CTL.";
		case    266: return "SCSI on ST.";
		case    267: return "Tobit David Service Layer.";
		case    268: return "Tobit David Replica.";
		case    280: return "http-mgmt.";
		case    281: return "Personal Link.";
		case    282: return "Cable Port A/X.";
		case    283: return "rescap.";
		case    284: return "corerjd.";
		case    286: return "FXP-1.";
		case    287: return "K-BLOCK.";
		case    308: return "Novastor Backup.";
		case    309: return "EntrustTime.";
		case    310: return "bhmds.";
		case    311: return "AppleShare IP WebAdmin.";
		case    312: return "VSLMP.";
		case    313: return "Magenta Logic.";
		case    314: return "Opalis Robot.";
		case    315: return "DPSI.";
		case    316: return "decAuth.";
		case    317: return "Zannet.";
		case    318: return "TSP, Time Stamp Protocol.";
		case    319: return "PTP Event.";
		case    320: return "PTP General.";
		case    321: return "PIP.";
		case    322: return "RTSPS.";
		case    323: return "IMMP, Internet Message Mapping Protocol.";
		case    333: return "Texar Security Port.";
		case    344: return "Prospero Data Access Protocol.";
		case    345: return "Performance Analysis Workbench.";
		case    346: return "Zebra server.";
		case    347: return "Fatmen Server.";
		case    348: return "Cabletron Management Protocol.";
		case    349: return "mftp.";
		case    350: return "MATIP, Mapping of Airline Traffic over Internet Protocol, Type A.";
		case    351: return "MATIP, Mapping of Airline Traffic over Internet Protocol, Type B. bhoetty.";
		case    352: return "DTAG.";
		case    353: return "NDSAUTH.";
		case    354: return "bh611.";
		case    355: return "DATEX-ASN.";
		case    356: return "Cloanto Net 1.";
		case    357: return "bhevent.";
		case    358: return "Shrinkwrap.";
		case    359: return "Tenebris Network Trace Service.";
		case    360: return "scoi2odialog.";
		case    361: return "Semantix.";
		case    362: return "SRS Send.";
		case    363: return "RSVP Tunnel.";
		case    364: return "Aurora CMGR.";
		case    365: return "DTK.";
		case    366: return "SMTP, Simple Mail Transfer Protocol. ODMR, On-Demand Mail Relay.";
		case    367: return "MortgageWare.";
		case    368: return "QbikGDP.";
		case    369: return "rpc2portmap. ";
		case    370: return "codaauth2.";
		case    371: return "Clearcase.";
		case    372: return "ListProcessor.";
		case    373: return "Legent Corporation.";
		case    374: return "Legent Corporation.";
		case    375: return "Hassle.";
		case    376: return "Amiga Envoy Network Inquiry Proto. ";
		case    377: return "NEC Corporation.";
		case    378: return "NEC Corporation.";
		case    379: return "TIA/EIA/IS-99 modem client.";
		case    380: return "TIA/EIA/IS-99 modem server.";
		case    381: return "HP performance data collector.";
		case    382: return "HP performance data managed node.";
		case    383: return "HP performance data alarm manager.";
		case    384: return "A Remote Network Server System.";
		case    385: return "IBM Application.";
		case    386: return "ASA Message Router Object Def.";
		case    387: return "AURP, AppleTalk Update-based Routing Protocol.";
		case    388: return "Unidata LDM Version 4.";
		case    389: return "LDAP, Lightweight Directory Access Protocol. CLDAP, Connection-less Lightweight X.500 Directory Access Protocol.";
		case    390: return "UIS.";
		case    391: return "SynOptics SNMP Relay Port.";
		case    392: return "SynOptics Port Broker Port.";
		case    393: return "Data Interpretation System.";
		case    394: return "EMBL Nucleic Data Transfer.";
		case    395: return "NETscout Control Protocol.";
		case    396: return "Novell Netware over IP.";
		case    397: return "Multi Protocol Trans. Net.";
		case    398: return "Kryptolan.";
		case    399: return "TP2 encapsulation.";
		case    400: return "Oracle Secure Backup.";
		case    401: return "Uninterruptible Power Supply.";
		case    402: return "Genie Protocol.";
		case    403: return "decap.";
		case    404: return "nced.";
		case    405: return "ncld.";
		case    406: return "Interactive Mail Support Protocol.";
		case    407: return "Timbuktu.";
		case    408: return "Prospero Resource Manager System Manager.";
		case    409: return "Prospero Resource Manager Node Manager.";
		case    410: return "DEC Ladebug Remote Debug Protocol.";
		case    411: return "Remote MT Protocol.";
		case    412: return "Trap Convention Port.";
		case    413: return "SMSP.";
		case    414: return "InfoSeek.";
		case    415: return "BNet.";
		case    416: return "Silverplatter.";
		case    417: return "Onmux.";
		case    418: return "Hyper-G.";
		case    419: return "Ariel.";
		case    420: return "SMPTE.";
		case    421: return "Ariel.";
		case    422: return "Ariel.";
		case    423: return "IBM Operations Planning and Control Start.";
		case    424: return "IBM Operations Planning and Control Track.";
		case    425: return "ICAD.";
		case    426: return "smartsdp";
		case    427: return "SLP, Service Location Protocol.";
		case    428: return "OCS_CMU.";
		case    429: return "OCS_AMU";
		case    430: return "UTMPSD";
		case    431: return "UTMPCD";
		case    432: return "IASD ";
		case    433: return "NNSP";
		case    434: return "Mobile IP agent.";
		case    435: return "Mobile IP MN.";
		case    436: return "DNA-CML ";
		case    437: return "comscm";
		case    438: return "dsfgw";
		case    439: return "dasp";
		case    440: return "sgcp";
		case    441: return "decvms-sysmgt";
		case    442: return "cvc_hostd";
		case    443: return "HTTPS, HTTP over SSL/TLS.";
		case    444: return "SNPP, Simple Network Paging Protocol.";
		case    445: return "Microsoft-DS.";
		case    446: return "DDM-RDB";
		case    447: return "DDM-RFM";
		case    448: return "DDM-SSL";
		case    449: return "AS Server Mapper";
		case    450: return "TServer";
		case    451: return "Cray Network Semaphore server";
		case    452: return "Cray SFS config server";
		case    453: return "CreativeServer";
		case    454: return "ContentServer";
		case    455: return "CreativePartnr";
		case    456: return "macon-tcp";
		case    457: return "scohelp";
		case    458: return "apple quick time";
		case    459: return "ampr-rcmd";
		case    460: return "skronk";
		case    461: return "DataRampSrv";
		case    462: return "DataRampSrvSec";
		case    463: return "alpes";
		case    464: return "Kerberos change/set password.";
		case    465: return "(TCP) URL Rendesvous Directory for SSM. (UDP) IGMP over UDP for SSM.";
		case    466: return "digital-vrc";
		case    467: return "mylex-mapd";
		case    468: return "Photuris.";
		case    469: return "Radio Control Protocol.";
		case    470: return "scx-proxy";
		case    471: return "Mondex.";
		case    472: return "ljk-login.";
		case    473: return "hybrid-pop.";
		case    474: return "(TCP) tn-tl-w1. (UDP) tn-tl-w2.";
		case    475: return "tcpnethaspsrv.";
		case    476: return "tn-tl-fd1.";
		case    477: return "ss7ns.";
		case    478: return "spsc.";
		case    479: return "iafserver.";
		case    480: return "iafdbase.";
		case    481: return "Ph service.";
		case    482: return "bgs-nsi.";
		case    483: return "ulpnet.";
		case    484: return "Integra Software Management Environment.";
		case    485: return "Air Soft Power Burst.";
		case    486: return "Avian.";
		case    487: return "SAFT, Simple Asynchronous File Transfer.";
		case    488: return "gss-http.";
		case    489: return "nest-protocol.";
		case    490: return "micom-pfs.";
		case    491: return "go-login.";
		case    492: return "Transport Independent Convergence for FNA.";
		case    493: return "Transport Independent Convergence for FNA.";
		case    494: return "POV-Ray.";
		case    495: return "intecourier.";
		case    496: return "PIM-RP-DISC.";
		case    497: return "dantz.";
		case    498: return "siam.";
		case    499: return "ISO ILL Protocol.";
		case    500: return "ISAKMP. IKE, Internet Key Exchange.";
		case    501: return "STMF.";
		case    502: return "asa-appl-proto.";
		case    503: return "Intrinsa.";
		case    504: return "citadel.";
		case    505: return "mailbox-lm.";
		case    506: return "ohimsrv.";
		case    507: return "crs.";
		case    508: return "xvttp.";
		case    509: return "snare.";
		case    510: return "FirstClass Protocol.";
		case    511: return "mynet-as.";
		case    512: return "rexec, remote process execution. Used by mail system to notify users of new mail received.";
		case    513: return "Rlogin. Maintains data bases for who's logged on a local net and the average load of the machine.";
		case    514: return "Syslog. cmd like exec but automatic authentication is performed for login server.";
		case    515: return "LPR.";
		case    516: return "videotex.";
		case    517: return "Like tenex link but across machine - doesn't use link protocol. A rendezvous port establishes a tcp connection.";
		case    518: return "ntalk.";
		case    519: return "unixtime.";
		case    520: return "RIP, Routing Information Protocol. Extended file name server.";
		case    521: return "RIPng.";
		case    522: return "ULP.";
		case    523: return "IBM-DB2.";
		case    524: return "NCP.";
		case    525: return "timeserver.";
		case    526: return "newdate.";
		case    527: return "Stock IXChange.";
		case    528: return "Customer IXChange.";
		case    529: return "IRC-SERV.";
		case    530: return "rpc.";
		case    531: return "chat.";
		case    532: return "readnews.";
		case    533: return "emergency broadcasts.";
		case    534: return "MegaMedia Admin.";
		case    535: return "iiop.";
		case    536: return "opalis-rdv.";
		case    537: return "Networked Media Streaming Protocol.";
		case    538: return "gdomap.";
		case    539: return "Apertus Technologies Load Determination.";
		case    540: return "uucpd.";
		case    541: return "uucp-rlogin. ";
		case    542: return "commerce.";
		case    543: return "klogin.";
		case    544: return "krcmd.";
		case    545: return "appleqtcsrvr.";
		case    546: return "DHCPv6 client.";
		case    547: return "DHCPv6 server.";
		case    548: return "AFP over TCP.";
		case    549: return "IDFP.";
		case    550: return "new-who.";
		case    551: return "cybercash.";
		case    552: return "deviceshare.";
		case    553: return "pirp.";
		case    554: return "RTSP, Real Time Streaming Protocol.";
		case    555: return "dsf.";
		case    556: return "rfs server.";
		case    557: return "openvms-sysipc.";
		case    558: return "SDNSKMP.";
		case    559: return "TEEDTAP.";
		case    560: return "rmonitord.";
		case    561: return "monitor.";
		case    562: return "chcmd.";
		case    563: return "NNTP over TLS.";
		case    564: return "plan 9 file service.";
		case    565: return "whoami.";
		case    566: return "streettalk.";
		case    567: return "banyan-rpc.";
		case    568: return "microsoft shuttle.";
		case    569: return "microsoft rome.";
		case    570: return "demon.";
		case    571: return "udemon.";
		case    572: return "sonar.";
		case    573: return "banyan-vip.";
		case    574: return "FTP Software Agent System.";
		case    575: return "VEMMI, VErsatile MultiMedia Interface.";
		case    576: return "ipcd.";
		case    577: return "vnas.";
		case    578: return "ipdd.";
		case    579: return "decbsrv.";
		case    580: return "SNTP HEARTBEAT.";
		case    581: return "Bundle Discovery Protocol.";
		case    582: return "SCC Security.";
		case    583: return "Philips Video-Conferencing.";
		case    584: return "Key Server.";
		case    586: return "Password Change.";
		case    587: return "ESMTP, Extended Simple Mail Transfer Protocol.";
		case    588: return "CAL.";
		case    589: return "EyeLink.";
		case    590: return "TNS CML.";
		case    591: return "FileMaker Inc. - HTTP Alternate (see Port 80).";
		case    592: return "Eudora Set.";
		case    593: return "HTTP RPC Ep Map.";
		case    594: return "TPIP.";
		case    595: return "CAB Protocol.";
		case    596: return "SMSD.";
		case    597: return "PTC Name Service.";
		case    598: return "SCO Web Server Manager 3.";
		case    599: return "Aeolon Core Protocol.";
		case    600: return "Sun IPC server.";
		case    601: return "Syslog.";
		case    602: return "XML-RPC over BEEP.";
		case    603: return "IDXP, Intrusion Detection Exchange Protocol.";
		case    604: return "TUNNEL.";
		case    605: return "SOAP over BEEP.";
		case    606: return "Cray Unified Resource Manager.";
		case    607: return "nqs.";
		case    608: return "SIFT/UFT, Sender-Initiated/Unsolicited File Transfer.";
		case    609: return "npmp-trap.";
		case    610: return "npmp-local.";
		case    611: return "npmp-gui. ";
		case    612: return "HMMP Indication.";
		case    613: return "HMMP Operation.";
		case    614: return "SSLshell.";
		case    615: return "Internet Configuration Manager.";
		case    616: return "SCO System Administration Server.";
		case    617: return "SCO Desktop Administration Server.";
		case    618: return "DEI-ICDA.";
		case    619: return "Digital EVM.";
		case    620: return "SCO WebServer Manager.";
		case    621: return "ESCP.";
		case    622: return "Collaborator.";
		case    623: return "DMTF out-of-band web services management protocol. Aux Bus Shunt. ASF Remote Management and Control Protocol.";
		case    624: return "Crypto Admin.";
		case    625: return "DEC DLM.";
		case    626: return "ASIA.";
		case    627: return "CKS &amp; TIVIOLI.";
		case    628: return "QMQP.";
		case    629: return "3Com AMP3.";
		case    630: return "RDA.";
		case    631: return "IPP, Internet Printing Protocol.";
		case    632: return "bmpp.";
		case    633: return "Service Status update (Sterling Software).";
		case    634: return "ginad.";
		case    635: return "RLZ DBase.";
		case    636: return "ldap protocol over TLS/SSL (was sldap).";
		case    637: return "lanserver.";
		case    638: return "mcns-sec.";
		case    639: return "MSDP, Multicast Source Discovery Protocol.";
		case    640: return "entrust-sps.";
		case    641: return "repcmd.";
		case    642: return "EMSD over ESRO.";
		case    643: return "SANity.";
		case    644: return "dwr.";
		case    645: return "PSSC.";
		case    646: return "LDP, Label Distribution Protocol.";
		case    647: return "DHCP Failover Protocol.";
		case    648: return "RRP, Registry Registrar Protocol.";
		case    649: return "Aminet.";
		case    650: return "OBEX.";
		case    651: return "IEEE MMS.";
		case    652: return "DTCP, Dynamic Tunnel Configuration Protocol.";
		case    653: return "RepCmd.";
		case    654: return "AODV, Ad hoc On-Demand Distance Vector.";
		case    655: return "TINC.";
		case    656: return "SPMP.";
		case    657: return "RMC.";
		case    658: return "TenFold.";
		case    659: return "URL Rendezvous.";
		case    660: return "MacOS Server Admin.";
		case    661: return "HAP.";
		case    662: return "PFTP.";
		case    663: return "PureNoise.";
		case    664: return "DMTF out-of-band secure web services management protocol. ASF Secure Remote Management and Control Protocol. Secure Aux Bus.";
		case    665: return "Sun DR.";
		case    666: return "Doom, Id Software.";
		case    667: return "Campaign contribution campaign contribution disclosures - SDR Technologies.";
		case    668: return "MeComm.";
		case    669: return "MeRegister.";
		case    670: return "VACDSM-SWS.";
		case    671: return "VACDSM-APP.";
		case    672: return "VPPS-QUA.";
		case    673: return "CIMPLEX.";
		case    674: return "ACAP, Application Configuration Access Protocol.";
		case    675: return "DCTP.";
		case    676: return "VPPS Via.";
		case    677: return "Virtual Presence Protocol.";
		case    678: return "GNU Gereration Foundation NCP.";
		case    679: return "MRM.";
		case    680: return "entrust-aaas.";
		case    681: return "entrust-aaas.";
		case    682: return "XFR.";
		case    683: return "CORBA IIOP.";
		case    684: return "CORBA IIOP SSL.";
		case    685: return "MDC Port Mapper.";
		case    686: return "Hardware Control Protocol Wismar.";
		case    687: return "asipregistry.";
		case    688: return "REALM-RUSD.";
		case    689: return "NMAP.";
		case    690: return "VATP.";
		case    691: return "MS Exchange Routing.";
		case    692: return "Hyperwave-ISP.";
		case    693: return "connendp.";
		case    694: return "ha-cluster.";
		case    695: return "IEEE-MMS-SSL.";
		case    696: return "RUSHD.";
		case    697: return "UUIDGEN.";
		case    698: return "OLSR, Optimized Link State Routing.";
		case    699: return "Access Network.";
		case    700: return "EPP, Extensible Provisioning Protocol.";
		case    701: return "LMP, Link Management Protocol.";
		case    702: return "IRIS over  BEEP.";
		case    704: return "errlog copy/server daemon.";
		case    705: return "AgentX.";
		case    706: return "SILC, Secure Internet Live Conferencing.";
		case    707: return "Borland DSJ.";
		case    709: return "Entrust Key Management Service Handler.";
		case    710: return "Entrust Administration Service Handler.";
		case    711: return "TDP, Tag Distribution Protocol.";
		case    712: return "TBRPF, Topology Broadcast based on Reverse-Path Forwarding.";
		case    713: return "IRIS over XPC.";
		case    714: return "IRIS over XPCS (RFC 4992).";
		case    715: return "IRIS-LWZ (RFC 4993).";
		case    716: return "PANA, Protocol for Carrying Authentication for Network Access.";
		case    720: return "DVMP, Distance Vectored Monitoring Protocol. SMQP, Simple Message Queue Protocol.";
		case    721: return "XSRP, eXtensible Service Registration Protocol.";
		case    723: return "XSTP, eXtensible Service Transfer Protocol.";
		case    725: return "XSSP, eXtensible Service Subscription Protocol.";
		case    727: return "XSLP, eXtensible Service Location Protocol.";
		case    729: return "IBM NetView DM/6000 Server/Client.";
		case    730: return "IBM NetView DM/6000 send TCP.";
		case    731: return "IBM NetView DM/6000 receive TCP.";
		case    741: return "netGW.";
		case    742: return "Network based Rev. Cont. Sys.";
		case    744: return "Flexible License Manager.";
		case    747: return "Fujitsu Device Control.";
		case    748: return "Russell Info Sci Calendar Manager.";
		case    749: return "kerberos administration.";
		case    750: return "kerberos version iv.";
		case    751: return "pump.";
		case    752: return "qrh.";
		case    753: return "rrh.";
		case    754: return "send";
		case    758: return "nlogin.";
		case    759: return "con.";
		case    760: return "ns.";
		case    761: return "rxe.";
		case    762: return "quotad.";
		case    763: return "cycleserv.";
		case    764: return "omserv.";
		case    765: return "webster.";
		case    767: return "phone.";
		case    769: return "vid.";
		case    770: return "cadlock.";
		case    771: return "rtip.";
		case    772: return "cycleserv2.";
		case    773: return "submit.";
		case    774: return "rpasswd. acmaint_dbd.";
		case    775: return "entomb. acmaint_transd.";
		case    776: return "wpages.";
		case    777: return "Multiling HTTP.";
		case    780: return "wpgs.";
		case    800: return "mdbs_daemon.";
		case    801: return "device.";
		case    810: return "FCP.";
		case    828: return "itm-mcell-s.";
		case    829: return "CMP, Certificate Management Protocols.";
		case    830: return "NETCONF over SSH.";
		case    831: return "NETCONF over BEEP.";
		case    832: return "NETCONF for  SOAP over HTTP.";
		case    833: return "NETCONF for  SOAP over BEEP.";
		case    847: return "dhcp-failover 2.";
		case    848: return "GDOI, Group Domain of Interpretation.";
		case    860: return "iSCSI.";
		case    861: return "OWAMP, One-way Active Measurement Protocol.";
		case    862: return "TWAMP, Two-Way Active Measurement Protocol.";
		case    873: return "rsync.";
		case    886: return "ICL coNETion locate server.";
		case    887: return "ICL coNETion server info.";
		case    888: return "AccessBuilder. CD Database Protocol.";
		case    900: return "OMG Initial Refs.";
		case    901: return "SMPNAMERES.";
		case    902: return "IDEAFARM-CHAT.";
		case    903: return "IDEAFARM-CATCH.";
		case    910: return "KINK, Kerberized Internet Negotiation of Keys.";
		case    911: return "xact-backup.";
		case    912: return "APEX relay-relay service.";
		case    913: return "APEX endpoint-relay service.";
		case    989: return "FTP data over TLS/SSL.";
		case    990: return "FTP control over TLS/SSL.";
		case    991: return "NAS, Netnews Administration System.";
		case    992: return "telnet over TLS/SSL.";
		case    993: return "imap4 over TLS/SSL.";
		case    994: return "irc over TLS/SSL.";
		case    995: return "pop3 over TLS/SSL (was spop3).";
		case    996: return "vsinet.";
		case    997: return "maitrd.";
		case    998: return "busboy. puparp.";
		case    999: return "Applix ac. garcon. puprouter.";
		case    1000: return "cadlock2.";
		case    1008: return "Sun Solaris?";
		case    1010: return "surf.";
		case    1021: return "RFC 3692-style Experiment 1.";
		case    1022: return "RFC 3692-style Experiment 2.";
		case    1023: return "reserved.";
			
		default:
			return "";
	}
}
